name: Run tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ecommerce_app
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.10.0
    - run: flutter test
